gravity:
  gunicorn:
    bind: 0.0.0.0:8080
    workers: 2
    extra_ars: '--forwarded-allow-ips="*"'
    preload: true
  celery:
    concurrency: 2
    loglevel: WARNING
  # handlers:
  #   handler:
  #     processes: 2
  #     pools:
  #       - job-handlers
  #       - workflow-schedulers
  gx_it_proxy:
  tusd:
  reports:
  process_manager: supervisor
  virtualenv: /galaxy/server/.venv
  galaxy_root: /galaxy/server
  galaxy_user: galaxy

galaxy:
  # Main config
  admin_users:
   - admin@example.org
  bootstrap_admin_api_key: 'iamanadminyouknow'
  object_store_store_by: uuid
  id_secret: 'morestufftoreplace'

  # Data connections
  #amqp_internal_connection: 'amqp://hello:world@rabbitmq:5672//'
  database_connection: postgresql://galaxy:galaxy@galaxy-postgres/galaxy

  # Job configuration
  cleanup_job: never
  data_dir: /galaxy/server/database
  enable_celery_tasks: true
  
  # Automation / Ease of Use / User-facing features
  watch_job_rules: 'auto'
  allow_path_paste: true
  enable_quotas: true
  allow_user_deletion: true
  show_welcome_with_login: true
  expose_user_name: true
  expose_dataset_path: true
  expose_potentially_sensitive_job_metrics: true

  # Tool security
  outputs_to_working_directory: true
  new_user_dataset_access_role_default_private: true

  # SQL Performance
  slow_query_log_threshold: 5
  enable_per_request_sql_debugging: true

  # File serving Performance
  nginx_x_accel_redirect_base: /_x_accel_redirect

  # NFS workarounds
  retry_job_output_collection: 3

  # Debugging
  cleanup_job: onsuccess
  allow_user_impersonation: true
 
  # File paths
  builds_file_path: /galaxy/server/tool-data/shared/ucsc/builds.txt.sample
  container_resolvers_config_file: ''
  data_manager_config_file: /galaxy/server/config/data_manager_conf.xml.sample
  datatypes_config_file: /galaxy/server/config/datatypes_conf.xml
  #dependency_resolvers_config_file: /galaxy/server/config/dependency_resolvers_conf.xml
  external_service_type_config_file: /galaxy/server/config/external_service_types_conf.xml.sample
  file_path: /galaxy/server/database/datasets
  integrated_tool_panel_config: /galaxy/server/config/integrated_tool_panel.xml
  job_metrics_config_file: /galaxy/server/config/job_metrics_conf.xml
  job_working_directory: /galaxy/server/database/jobs
  migrated_tools_config: /galaxy/server/config/migrated_tools_conf.xml
  openid_config_file: /galaxy/server/config/openid_conf.xml.sample
  shed_data_manager_config_file: /galaxy/server/config/shed_data_manager_conf.xml
  shed_tool_config_file: /galaxy/server/config/shed_tool_conf.xml
  shed_tool_data_table_config: /galaxy/server/config/shed_tool_data_table_conf.xml
  tool_config_file: /galaxy/server/config/tool_conf.xml.sample
  job_config_file: /galaxy/server/config/job_conf.xml
  tool_data_path: /galaxy/server/database/tool_data
  tool_data_table_config_path: /galaxy/server/config/tool_data_table_conf.xml.sample
  tool_dependency_dir: /galaxy/server/database/dependencies
  tool_sheds_config_file: /galaxy/server/config/tool_sheds_conf.xml.sample
  ucsc_build_sites: /galaxy/server/tool-data/shared/ucsc/ucsc_build_sites.txt.sample
  visualization_plugins_directory: config/plugins/visualizations
